[[agents]]
id = "test agent"
name = "Holo Tester"
key_file = "holo_tester.key"

[[dnas]]
id = "chat"
file = "C:/Users/Ashan/Documents/holochain/holochat-rust/dist/bundle.json"
hash = "Qm328wyq38924y"

[[instances]]
id = "chat"
dna = "chat"
agent = "test agent"
[instances.logger]
type = "simple"
file = "app_spec.log"
[instances.storage]
type = "file"
path = "tmp-storage"


[[interfaces]]
id = "websocket interface"
[interfaces.driver]
type = "websocket"
port = 3400
[[interfaces.instances]]
id = "chat"
